# Generated by Django 2.2.4 on 2019-08-20 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('import_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_id', models.IntegerField()),
                ('town', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=256)),
                ('building', models.CharField(max_length=256)),
                ('apartment', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=10)),
                ('data_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizens', to='dataimports.DataImport')),
                ('relatives', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataimports.Citizen')),
            ],
        ),
    ]
