# Generated by Django 2.2.4 on 2019-08-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='relatives',
        ),
        migrations.AddField(
            model_name='citizen',
            name='relatives',
            field=models.ManyToManyField(null=True, related_name='_citizen_relatives_+', to='dataimports.Citizen'),
        ),
    ]
