# Generated by Django 2.2.4 on 2019-08-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimports', '0002_auto_20190821_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='relatives',
            field=models.ManyToManyField(blank=True, related_name='_citizen_relatives_+', to='dataimports.Citizen'),
        ),
    ]
