# Generated by Django 2.2.4 on 2019-08-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataimports', '0003_auto_20190821_0835'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citizen',
            unique_together={('data_import', 'citizen_id')},
        ),
    ]
