# Generated by Django 2.2.4 on 2019-08-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimports', '0005_auto_20190821_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='apartment',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='citizen_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='relatives',
            field=models.ManyToManyField(blank=True, related_name='_citizen_relatives_+', to='dataimports.Citizen'),
        ),
    ]
