# Generated by Django 2.2.4 on 2019-08-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimports', '0006_auto_20190821_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10),
        ),
    ]
